name: 'Setup Neovim'
description: 'Install Neovim nightly on Ubuntu, macOS, or Windows'
inputs:
  arch:
    description: 'Architecture (x64 or arm64). Auto-detects if not specified.'
    required: false
    default: ''
runs:
  using: 'composite'
  steps:
    - name: Install Neovim (Ubuntu)
      if: runner.os == 'Linux'
      shell: bash
      run: |
        # Auto-detect architecture if not specified
        INPUT_ARCH="${{ inputs.arch }}"
        if [ -z "$INPUT_ARCH" ]; then
          if [ "$(uname -m)" = "aarch64" ]; then
            INPUT_ARCH="arm64"
          else
            INPUT_ARCH="x64"
          fi
        fi
        
        ARCH="linux-x86_64"
        if [ "$INPUT_ARCH" = "arm64" ]; then
          ARCH="linux-arm64"
        fi
        curl -LO https://github.com/neovim/neovim/releases/download/nightly/nvim-$ARCH.tar.gz
        tar xzf nvim-$ARCH.tar.gz
        sudo cp -r nvim-$ARCH/* /usr/local/
        nvim --version | head -n 1

    - name: Install Neovim (macOS)
      if: runner.os == 'macOS'
      shell: bash
      run: |
        # Auto-detect architecture if not specified
        INPUT_ARCH="${{ inputs.arch }}"
        if [ -z "$INPUT_ARCH" ]; then
          if [ "$(uname -m)" = "arm64" ]; then
            INPUT_ARCH="arm64"
          else
            INPUT_ARCH="x64"
          fi
        fi
        
        ARCH="macos-arm64"
        if [ "$INPUT_ARCH" = "x64" ]; then
          ARCH="macos-x86_64"
        fi
        curl -LO https://github.com/neovim/neovim/releases/download/nightly/nvim-$ARCH.tar.gz
        tar xzf nvim-$ARCH.tar.gz
        sudo cp -r nvim-$ARCH/* /usr/local/
        nvim --version | head -n 1

    - name: Install Neovim (Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        # Auto-detect architecture if not specified
        $arch = "${{ inputs.arch }}"
        if ([string]::IsNullOrEmpty($arch)) {
          if ($env:PROCESSOR_ARCHITECTURE -eq "ARM64") {
            $arch = "arm64"
          } else {
            $arch = "x64"
          }
        }
        
        $archSuffix = if ($arch -eq "arm64") { "-arm64" } else { "64" }
        $downloadUrl = "https://github.com/neovim/neovim/releases/download/nightly/nvim-win$archSuffix.zip"
        $installPath = "C:\tools\neovim"
        
        Write-Host "Downloading Neovim from $downloadUrl"
        Invoke-WebRequest -Uri $downloadUrl -OutFile "$env:TEMP\nvim.zip"
        
        New-Item -ItemType Directory -Force -Path $installPath | Out-Null
        Expand-Archive -Path "$env:TEMP\nvim.zip" -DestinationPath $installPath -Force
        
        $nvimBinPath = "$installPath\nvim-win$archSuffix\bin"
        echo "$nvimBinPath" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        
        & "$nvimBinPath\nvim.exe" --version | Select-Object -First 1
